[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BOOKIE"
authors = [{name = "Germán Rodríguez-Galán", email = "german.rodriguez@epn.edu.ec"}]
dynamic = ["version", "description"]
